# DATA EXPLORATION - VANGUARD A/B TEST
---

Digital Footprints: A detailed trace of client interactions online
**Question was: Would these changes encourage more clients to complete the process?**

IMPORT LIBRARIES

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

sns.set_style("whitegrid")

1. LOAD THE DATASETS

In [2]:
data_path = "data/raw_data"
df_web_1 = pd.read_csv(f"{data_path}/df_final_web_data_pt_1.txt")
df_web_2 = pd.read_csv(f"{data_path}/df_final_web_data_pt_2.txt")
df_experiment = pd.read_csv(f"{data_path}/df_final_experiment_clients.txt")

## Phase 1 — EDA & Data Cleaning

DATASET: Web_1

In [3]:
df_web_1.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [4]:
df_web_1.shape

(343141, 5)

In [5]:
df_web_1["client_id"].nunique()

58391

DATASET: Web_2

In [6]:
df_web_2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [7]:
df_web_2.shape

(412264, 5)

In [8]:
df_web_2["client_id"].nunique()

67430

In [9]:
# merging both databases
df_web_3 = pd.concat([df_web_1,df_web_2], axis = 0, ignore_index = True)
df_web_3

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [10]:
web = df_web_3.merge(df_experiment, on='client_id', how='inner')

In [11]:
web.head(10)

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
5,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15,Test
6,9988021,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01,Test
7,9988021,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22,Test
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05,Test
9,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43,Test

In [12]:
#renaming columns
web.columns = web.columns.str.lower().str.replace(' ', '_')

In [13]:
web.dtypes

client_id        int64
visitor_id      object
visit_id        object
process_step    object
date_time       object
variation       object
dtype: object

**Dealing with NULL VALUES**

In [14]:
# finding nulls
web.isna().sum()

client_id            0
visitor_id           0
visit_id             0
process_step         0
date_time            0
variation       128522
dtype: int64

In [15]:
web.dropna(subset=['variation'], inplace=True)

**Sorting Date_time Column**

In [16]:
web['date_time'] = pd.to_datetime(web['date_time'])

In [17]:
web = web.sort_values(by=['client_id', 'visit_id', 'date_time'])

In [18]:
web['next_time'] = web.groupby(['client_id', 'visit_id'])['date_time'].shift(-1)

In [19]:
web['sec_spent'] = (web['next_time'] - web['date_time']).dt.total_seconds()

In [20]:
web.head(10)

,client_id,visitor_id,visit_id,process_step,date_time,variation,next_time,sec_spent
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,2017-04-15 12:58:03,7.0
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,2017-04-15 12:58:35,32.0
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2017-04-15 13:00:14,99.0
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,2017-04-15 13:00:34,20.0
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,NaT,NaN
135918,647,66758770_53988066587,40369564_40101682850_311847,start,2017-04-12 15:41:28,Test,2017-04-12 15:41:35,7.0
135917,647,66758770_53988066587,40369564_40101682850_311847,step_1,2017-04-12 15:41:35,Test,2017-04-12 15:41:53,18.0
135916,647,66758770_53988066587,40369564_40101682850_311847,step_2,2017-04-12 15:41:53,Test,2017-04-12 15:45:02,189.0
135915,647,66758770_53988066587,40369564_40101682850_311847,step_3,2017-04-12 15:45:02,Test,2017-04-12 15:47:45,163.0
135912,647,66758770_53988066587,40369564_40101682850_311847,confirm,2017-04-12 15:47:45,Test,NaT,NaN

In [21]:
web['process_order'] = web.groupby(['client_id', 'visit_id'])['process_step'].shift(-1)

In [22]:
web.head()

,client_id,visitor_id,visit_id,process_step,date_time,variation,next_time,sec_spent,process_order
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,2017-04-15 12:58:03,7.0,step_1
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,2017-04-15 12:58:35,32.0,step_2
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2017-04-15 13:00:14,99.0,step_3
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,2017-04-15 13:00:34,20.0,confirm
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,NaT,NaN,NaN

In [23]:
web.head()

,client_id,visitor_id,visit_id,process_step,date_time,variation,next_time,sec_spent,process_order
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,2017-04-15 12:58:03,7.0,step_1
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,2017-04-15 12:58:35,32.0,step_2
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2017-04-15 13:00:14,99.0,step_3
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,2017-04-15 13:00:34,20.0,confirm
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,NaT,NaN,NaN

In [24]:
correct_order = ['start', 'step_1', 'step_2', 'step_3', 'confirm']

In [25]:
expected_next = {
    'start': 'step_1',
    'step_1': 'step_2',
    'step_2': 'step_3',
    'step_3': 'confirm',
    'confirm': None
}

In [26]:
def check_row(row):
    current = row['process_step']
    actual_next = row['process_order']
    expected = expected_next.get(current)
    
    # repeated
    if current == actual_next:
        return "repeated"
    
    # correct
    if expected == actual_next:
        return "correct"
    
    # handle last step (confirm → NaN)
    if expected is None and pd.isna(actual_next):
        return "correct"
    
    return "error"

In [27]:
web['process_status'] = web.apply(check_row, axis=1)

In [28]:
web.head()

,client_id,visitor_id,visit_id,process_step,date_time,variation,next_time,sec_spent,process_order,process_status
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,2017-04-15 12:58:03,7.0,step_1,correct
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,2017-04-15 12:58:35,32.0,step_2,correct
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2017-04-15 13:00:14,99.0,step_3,correct
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,2017-04-15 13:00:34,20.0,confirm,correct
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,NaT,NaN,NaN,correct

In [29]:
web = web.reindex(columns=['client_id', 'visitor_id', 'visit_id', 'process_step','process_order', 'process_status', 'date_time', 'next_time', 'sec_spent', 'variation'])

In [30]:
web.head(50)

,client_id,visitor_id,visit_id,process_step,process_order,process_status,date_time,next_time,sec_spent,variation
70803,555,402506806_56087378777,637149525_38041617439_716659,start,step_1,correct,2017-04-15 12:57:56,2017-04-15 12:58:03,7.0,Test
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,step_2,correct,2017-04-15 12:58:03,2017-04-15 12:58:35,32.0,Test
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,step_3,correct,2017-04-15 12:58:35,2017-04-15 13:00:14,99.0,Test
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,confirm,correct,2017-04-15 13:00:14,2017-04-15 13:00:34,20.0,Test
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,NaN,correct,2017-04-15 13:00:34,NaT,NaN,Test
135918,647,66758770_53988066587,40369564_40101682850_311847,start,step_1,correct,2017-04-12 15:41:28,2017-04-12 15:41:35,7.0,Test
135917,647,66758770_53988066587,40369564_40101682850_311847,step_1,step_2,correct,2017-04-12 15:41:35,2017-04-12 15:41:53,18.0,Test
135916,647,66758770_53988066587,40369564_40101682850_311847,step_2,step_3,correct,2017-04-12 15:41:53,2017-04-12 15:45:02,189.0,Test
135915,647,66758770_53988066587,40369564_40101682850_311847,step_3,confirm,correct,2017-04-12 15:45:02,2017-04-12 15:47:45,163.0,Test
135912,647,66758770_53988066587,40369564_40101682850_311847,confirm,NaN,correct,2017-04-12 15:47:45,NaT,NaN,Test
61559,934,810392784_45004760546,7076463_57954418406_971348,start,start,repeated,2017-04-18 02:36:30,2017-04-18 02:37:02,32.0,Test
61558,934,810392784_45004760546,7076463_57954418406_971348,start,start,repeated,2017-04-18 02:37:02,2017-04-18 02:38:24,82.0,Test
61557,934,810392784_45004760546,7076463_57954418406_971348,start,start,repeated,2017-04-18 02:38:24,2017-04-18 02:38:52,28.0,Test
61556,934,810392784_45004760546,7076463_57954418406_971348,start,NaN,error,2017-04-18 02:38:52,NaT,NaN,Test
130234,1028,42237450_62128060588,557292053_87239438319_391157,start,step_1,correct,2017-04-08 18:51:28,2017-04-08 18:52:17,49.0,Control
130233,1028,42237450_62128060588,557292053_87239438319_391157,step_1,step_1,repeated,2017-04-08 18:52:17,2017-04-08 18:53:20,63.0,Control
130232,1028,42237450_62128060588,557292053_87239438319_391157,step_1,step_2,correct,2017-04-08 18:53:20,2017-04-08 18:53:29,9.0,Control
130231,1028,42237450_62128060588,557292053_87239438319_391157,step_2,step_3,correct,2017-04-08 18:53:29,2017-04-08 18:58:04,275.0,Control
130230,1028,42237450_62128060588,557292053_87239438319_391157,step_3,step_1,error,2017-04-08 18:58:04,2017-04-08 18:59:55,111.0,Control
130229,1028,42237450_62128060588,557292053_87239438319_391157,step_1,step_1,repeated,2017-04-08 18:59:55,2017-04-08 19:00:15,20.0,Control
130228,1028,42237450_62128060588,557292053_87239438319_391157,step_1,step_2,correct,2017-04-08 19:00:15,2017-04-08 19:00:17,2.0,Control
130227,1028,42237450_62128060588,557292053_87239438319_391157,step_2,step_1,error,2017-04-08 19:00:17,2017-04-08 19:00:26,9.0,Control
130226,1028,42237450_62128060588,557292053_87239438319_391157,step_1,NaN,error,2017-04-08 19:00:26,NaT,NaN,Control
347026,1104,194240915_18158000533,543158812_46395476577_767725,start,NaN,error,2017-06-12 07:49:18,NaT,NaN,Control
347038,1104,194240915_18158000533,643221571_99977972121_69283,start,NaN,error,2017-06-20 22:31:33,NaT,NaN,Control
233499,1186,446844663_31615102958,507052512_11309370126_442139,start,NaN,error,2017-04-08 15:59:16,NaT,NaN,Control
233498,1186,446844663_31615102958,795373564_99931517312_810896,start,step_1,correct,2017-04-08 18:05:02,2017-04-08 18:05:13,11.0,Control
233497,1186,446844663_31615102958,795373564_99931517312_810896,step_1,step_2,correct,2017-04-08 18:05:13,2017-04-08 18:05:24,11.0,Control
233496,1186,446844663_31615102958,795373564_99931517312_810896,step_2,NaN,error,2017-04-08 18:05:24,NaT,NaN,Control
13143,1195,766842522_69992551638,393817425_39015278493_996341,start,step_1,correct,2017-04-05 20:15:26,2017-04-05 20:15:59,33.0,Control
13142,1195,766842522_69992551638,393817425_39015278493_996341,step_1,step_2,correct,2017-04-05 20:15:59,2017-04-05 20:17:37,98.0,Control
13141,1195,766842522_69992551638,393817425_39015278493_996341,step_2,step_3,correct,2017-04-05 20:17:37,2017-04-05 20:18:08,31.0,Control
13140,1195,766842522_69992551638,393817425_39015278493_996341,step_3,confirm,correct,2017-04-05 20:18:08,2017-04-05 20:19:31,83.0,Control
13139,1195,766842522_69992551638,393817425_39015278493_996341,confirm,NaN,correct,2017-04-05 20:19:31,NaT,NaN,Control
31200,1197,753759429_54481946928,71862471_21202285428_848395,start,step_1,correct,2017-04-01 17:16:24,2017-04-01 17:16:28,4.0,Control
31199,1197,753759429_54481946928,71862471_21202285428_848395,step_1,step_2,correct,2017-04-01 17:16:28,2017-04-01 17:16:34,6.0,Control
31198,1197,753759429_54481946928,71862471_21202285428_848395,step_2,step_3,correct,2017-04-01 17:16:34,2017-04-01 17:17:25,51.0,Control
31197,1197,753759429_54481946928,71862471_21202285428_848395,step_3,step_2,error,2017-04-01 17:17:25,2017-04-01 17:17:36,11.0,Control
31196,1197,753759429_54481946928,71862471_21202285428_848395,step_2,step_3,correct,2017-04-01 17:17:36,2017-04-01 17:17:42,6.0,Control
31195,1197,753759429_54481946928,71862471_21202285428_848395,step_3,confirm,correct,2017-04-01 17:17:42,2017-04-01 17:17:59,17.0,Control
31194,1197,753759429_54481946928,71862471_21202285428_848395,confirm,NaN,correct,2017-04-01 17:17:59,NaT,NaN,Control
405365,1336,920624746_32603333901,583743392_96265099036_939815,start,step_1,correct,2017-05-08 06:05:12,2017-05-08 06:05:37,25.0,Test
405364,1336,920624746_32603333901,583743392_96265099036_939815,step_1,step_2,correct,2017-05-08 06:05:37,2017-05-08 06:06:03,26.0,Test
405363,1336,920624746_32603333901,583743392_96265099036_939815,step_2,step_3,correct,2017-05-08 06:06:03,2017-05-08 06:06:54,51.0,Test
405362,1336,920624746_32603333901,583743392_96265099036_939815,step_3,confirm,correct,2017-05-08 06:06:54,2017-05-08 06:08:43,109.0,Test
405361,1336,920624746_32603333901,583743392_96265099036_939815,confirm,NaN,correct,2017-05-08 06:08:43,NaT,NaN,Test
405347,1336,920624746_32603333901,614001770_19101025926_112779,confirm,confirm,repeated,2017-05-08 08:21:38,2017-05-08 08:23:00,82.0,Test
405346,1336,920624746_32603333901,614001770_19101025926_112779,confirm,NaN,correct,2017-05-08 08:23:00,NaT,NaN,Test
376382,1346,123474046_4204671056,27144337_83739845380_214282,start,step_1,correct,2017-06-06 18:20:28,2017-06-06 18:20:36,8.0,Test
376381,1346,123474046_4204671056,27144337_83739845380_214282,step_1,start,error,2017-06-06 18:20:36,2017-06-06 18:23:51,195.0,Test

**Dealing with Duplicates**

In [31]:
# duplicates sum
df_web_3.duplicated().sum()

np.int64(10764)

## Descriptive Analysis

In [32]:
web["client_id"].nunique()

50500

In [33]:
web["visitor_id"].nunique()

56011

In [39]:
visit_counts = web.groupby('client_id')['visit_id'].nunique()
visit_counts[visit_counts > 1]

client_id
1104       2
1186       2
1336       2
1516       2
1643       3
          ..
9995265    2
9996404    2
9997470    3
9998964    2
9999729    3
Name: visit_id, Length: 12996, dtype: int64

In [34]:
web["process_step"].nunique()

5

In [35]:
web["sec_spent"].value_counts()

sec_spent
5.0       6337
4.0       6312
6.0       6207
7.0       5910
8.0       5650
          ...
1694.0       1
1286.0       1
1240.0       1
2178.0       1
1456.0       1
Name: count, Length: 1864, dtype: int64

In [36]:
web["sec_spent"].describe().round(2)

count    251862.00
mean         82.51
std         212.57
min           0.00
25%          12.00
50%          35.00
75%          81.00
max       40235.00
Name: sec_spent, dtype: float64

In [37]:
web["process_status"].value_counts()

process_status
correct     224975
error        59631
repeated     36703
Name: count, dtype: int64

## Exporting Database

In [38]:
# exporting database
output_dir = "data/processed"
os.makedirs(output_dir, exist_ok=True)

web.to_csv(f"{output_dir}/web.csv", index=False)

print("Exported:")
for f in os.listdir(output_dir):
    path = os.path.join(output_dir, f)
    size = os.path.getsize(path)
    print(f"  {f} ({size:,} bytes)")

Exported:
  df_exde.csv (3,302,143 bytes)
  df_web_3.csv (81,420,206 bytes)
  vanguard_client_summary.csv (1,354,845 bytes)
  vanguard_hypo.csv (3,884,978 bytes)
  vanguard_web_wrangled.csv (35,857,674 bytes)
  web.csv (40,471,437 bytes)